version: "3"
networks:
  shared_network:
    name: shared_network
    driver: bridge
services:
  streetvision-webapp:
    build:
      context: ./streetvision-webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps port 80 from the container to 3004 on the host
    depends_on:
      - streetvision-db
      - backend-service
    volumes:
      - ./streetvision-webapp:/usr/src/app
    networks:
      shared_network:
        aliases:
          - ui
  streetvision-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./appldb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - shared_network
  backend-service:
    build:
      context: ./backend-service
    volumes:
      - ./backend-service:/usr/src/app
    ports:
      - "9000:9000" # note to self, move all services to 9000 range
    # depends_on:
    # - kafka
    # - workflow-service
    environment:
      - MONGODB_URI=mongodb://streetvision-db:27017/appdb
      # - KAFKA_BROKER_URL=kafka:29092
      # - WORKFLOW_SERVICE_URL=http://workflow-service:9000
    networks:
      shared_network:
        aliases:
          - backend
  elasticsearch: #to test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es-data:/usr/share/elasticsearch/data # Persist data
    ports:
      - "9200:9200" # Expose Elasticsearch HTTP port
      - "9300:9300" # Expose Elasticsearch TCP port
    networks:
      - shared_network
