version: "3"
networks:
  shared_network:
    name: shared_network
    driver: bridge
services:
  web-app-applicant:
    build:
      context: ./smartvision-webapp
      dockerfile: Dockerfile
    ports:
      - "4004:80" # Maps port 80 from the container to 3004 on the host
    depends_on:
      - smartvision-db
    networks:
      shared_network:
        aliases:
          - ui
